### PR TITLE
Typos

### PR DESCRIPTION
**Pull request by tzanio**
Found with

```
codespell -q 3 -L allright,ba,bu,childs,equil,esy,fo,fom,hda,localy,lod,mone,nd,ned,nnumber,numer,ot,pres,ro,seh,shat,solfes,strat,tbe,te,tthe,warmup
```

See https://github.com/mfem/mfem/pull/3254

### CODE REVIEW

**Comment by tzanio** [comment]
ping: https://github.com/luzpaz

**Review by cjvogl — CHANGES_REQUESTED** [review]
Everything looks good, although one of the tests appears to have failed (perhaps from a change outside of this PR?).  If someone can confirm that test failing is "expected," I'll approve this PR.

**Comment by luzpaz** [comment]
Please merge #245 before merging this PR

**Comment by tzanio** [comment]
The CI failures in this PR are very likely because the `macos-latest` image for this repo was switched from [macos-11](https://github.com/GLVis/glvis/actions/runs/3011778060/jobs/4839201813#step:1:8) to [macos-12](https://github.com/GLVis/glvis/actions/runs/3282293609/jobs/5700530122#step:1:8) in the last two months.

[According to GitHub](https://github.blog/changelog/2022-10-03-github-actions-jobs-running-on-macos-latest-are-now-running-on-macos-12/) the transition will take place over 10 weeks starting October 3rd, 2022.

We can ignore the failures here, but we will have to address them eventually in the MFEM repo.

cc: @publixsubfan, @v-dobrev

**Comment by tzanio** [comment]
@cjvogl and @acfisher -- ignoring the CI failure (see [above](https://github.com/GLVis/glvis/pull/244#issuecomment-1307794619)), can you review please?

**Review by cjvogl — APPROVED** [review]
Looks good (although my spelling is terrible)!

**Review by acfisher — APPROVED** [review]
Yay for spellcheck!

**Pull request merged**
