### PR TITLE
Quadrature visualization support for glvis-js

### PR DESCRIPTION
**Pull request by justinlaughlin**
Eventually, we should refactor `aux_js.cpp` a bit so that there isn't so much repeated code with `glvis.cpp`. For now, this is just following the same design pattern to see if we can get quadrature support in `glvis-js`.

### CODE REVIEW

**Comment by justinlaughlin** [comment]
I think this fixed it? To test

```bash
git clone git@github.com:GLVis/glvis-js.git
cd glvis-js
git checkout ci-build-10626571587
open examples/basic.html # or open with a browser
# open glvis-data/streams/quadrature-lor.saved and press Q
```

**Comment by tzanio** [comment]
I can confirm `Q` works now. Thanks @justinlaughlin ~

**Review by tzanio — APPROVED** [review]

**Review by najlkin — COMMENTED** [review]
Yes, works for me too :wink: 🚀  I agree it would be better to unify the code with `glvis.cpp`, but there are some subtleties different, so it is not that easy.
However, I noticed that `updateStream()` has a hardcoded check for `solution`, so that needs to be fixed for mesh and quadrature 🤔

**Comment by justinlaughlin** [comment]
> Yes, works for me too 😉 🚀 I agree it would be better to unify the code with `glvis.cpp`, but there are some subtleties different, so it is not that easy. However, I noticed that `updateStream()` has a hardcoded check for `solution`, so that needs to be fixed for mesh and quadrature 🤔

`updateStream()` uses `StreamState::SetNewMeshAndSolution` which it looks like you updated already 🙂. I went ahead and removed the check; I don't see any downstream calls specific to `data_type`. I tested the build `ci-build-10706880188` and it seems okay to me.

**Review by najlkin — APPROVED** [review]
LGTM, the check in `updateStream` was superfluous, I think :wink:.

**Pull request merged**
