### PR TITLE
Build mfem sequential by default, parallel as a bonus

### PR DESCRIPTION
**Pull request by adrienbernede**
Following suggestions in https://github.com/GLVis/glvis/pull/164#issuecomment-819668445

### CODE REVIEW

**Comment by adrienbernede** [comment]
Done

**Review by tzanio — APPROVED** [review]

**Comment by v-dobrev** [comment]
Looking at check "builds / ubuntu-18.04-optim-sequential-make" above (https://github.com/GLVis/glvis/pull/167/checks?check_run_id=2355732537), it looks like it builds parallel mfem instead of serial.  It also builds mfem examples, miniapps, etc, which is not necessary.

**Comment by adrienbernede** [comment]
Good catch... I must have been distracted by the other bug I had.
Should be fixed now, but there is an issue with packages downloads on ubuntu, I’ll try again later.

Side note: I’m thinking of switching to pre-built containers to avoid those issues on repetitive tasks.

**Comment by v-dobrev** [comment]
What about
>  It also builds mfem examples, miniapps, etc, which is not necessary.

?

**Comment by adrienbernede** [comment]
This would require a change in the build-mfem action.
I can do it, but it will take a bit more work to do and validate.
Moreover, I think we could just have mfem master produce a container where MFEM is already installed and that other apps could use. I would give priority to this solution as it solves several issue and would save a lot of CI time.

**Comment by kanye-quest** [comment]
I noticed that sometimes the dependency installation will fail due to older package version in the ubuntu jobs, do we need to add a `sudo apt-get update` before the `apt-get install` action?

**Comment by adrienbernede** [comment]
> I noticed that sometimes the dependency installation will fail due to older package version in the ubuntu jobs, do we need to add a `sudo apt-get update` before the `apt-get install` action?

How did you find out it was due to older package version? I don’t see why this is only intermittent, but I can try your suggestion.

**Comment by kanye-quest** [comment]
That's my guess, since the build fails with:
```
E: Failed to fetch http://azure.archive.ubuntu.com/ubuntu/pool/main/s/systemd/libudev-dev_237-3ubuntu10.45_amd64.deb  404  Not Found [IP: 52.252.75.106 80]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

The website is up though, and has a package `libudev-dev_237-3ubuntu10.47_amd64.deb`, so it may be intermittent depending on if/when they purge older packages.

**Review by kanye-quest — APPROVED** [review]

**Pull request merged**
