### PR TITLE
Colormaps improvements

### LINKED ISSUE #100: Add support for Matplotlib's perceptually uniform colormaps
It may be nice to add the perceptually uniform colormaps `viridis`, `plasma`, `inferno`, `magma`, `cividis` from Matplotlib.

More information here: https://matplotlib.org/tutorials/colors/colormaps.html.

Here is a nice video explaining their design: https://youtu.be/xAoljeRJ3lU.

### PR DESCRIPTION
**Pull request by tzanio**
A couple of colormaps improvements:

- Added several perceptually uniform colormaps `turbo`, `viridis`, `plasma`, `fusion`, `iceburn`, `viola`, `pride` and `ocean` from
   + [Google AI](https://ai.googleblog.com/2019/08/turbo-improved-rainbow-colormap-for.html)
   + [Matplotlib](https://bids.github.io/colormap/)
   + [CMasher](https://github.com/1313e/CMasher)

- Added the ability to discretize a palette, i.e. to use just a prescribed number of its colors, see the new "number of colors" input of the `F6` key.

- Replaced the `deep sea` palette with `ocean`.

Resolves #100

 | PR | Author | Editor | Reviewers | Assignment | Approval | Merge| 
 | --- | --- | --- | --- | --- | --- | --- | 
| [#103](https://github.com/glvis/glvis/pull/103) | @tzanio | @v-dobrev | @v-dobrev + @pazner | 06/17/20 | 06/22/20 | 06/22/20 | |

### CODE REVIEW

**Comment by tzanio** [comment]
The new colormaps in action:

turbo
viridis
plasma
fusion
iceburn
viola
pride
ocean

**Comment by tzanio** [comment]
Any feedback on this?

**Comment by pazner** [comment]
The new colormaps look really good and the ability to discretize a palette is also nice. Perhaps it makes sense for the discretization option to come after selecting the palette in the F6 menu (otherwise the the denominator in the displayed number of colors won't reflect the new choice).

While testing, I somehow got into a state where the first two prompts in the F6 menu would be skipped, but I haven't been able to reproduce this.

**Comment by v-dobrev** [comment]
Looks good to me -- very nice addition.

I have not tested it myself, but it looks like @pazner already did that, so I think the PR is good to go.

@pazner, I think the issue with the palette menu may be related to how the input is processed in https://github.com/GLVis/glvis/blob/dd707f765c909a1579af36a5c8f0d3784e8428ed/lib/palettes.cpp#L7522
It is done differently to allow you to just hit enter to confirm the current value. However, it assumes one thing: there a newline symbol (optionally preceded by other unprocessed non-newline characters) in the input buffer that was not processed -- this is typically left there after input like this: `cin >> i` where `i` is say an integer. Such newline symbols are typically skipped by the next call to `cin >> j` but in `Select_New_RGB_Palette` it is skipped with the first call to `cin.getline()`. This way, if the next `cin.getline()` returns an empty string, we know to reuse the current value. I'm not sure what sequence of inputs lead to the issue you noticed but it is probably related to this specific way of processing the input.

**Comment by tzanio** [comment]
Thanks guys!

Veselin, do you think we should move the question for how many colors to use before or after the palette selection? Currently it looks like this:

```
Palette is repeated 1 times.
(Negative value means the palette is flipped.)
Enter new value: 1
Palette will be repeated 1 times now.

Palette is using 2/31 colors.
Enter new value (0=original): 20
Palette will be using 20/31 colors now.

Choose a palette:
   1) 5-color      2) red          3) jet-like     4) coldhot      5) bone      
   6) hot          7) pink         8) cool         9) summer      10) hsv       
  11) copper      12) white       13) vivid       14) aluminum    15) sunrise   
  16) horizon     17) byr         18) ocean       19) pastel      20) tropical  
  21) wood        22) mars        23) rainbow     24) cmyk        25) calewhite 
  26) haxby       27) manga       28) drywet      29) gfdl        30) wbgyr     
  31) seq25       32) terrain     33) bwor        34) 19-lev      35) lithology 
  36) gray        37) turbo       38) viridis     39) plasma      40) fusion    
  41) iceburn     42) viola       43) pride     
 ---> [24] 
```

**Comment by v-dobrev** [comment]
Oh, hmm. It seems more appropriate to move the "number of colors" question after choosing the palette.

**Comment by v-dobrev** [comment]
Also the `21/30` message might be somewhat confusing -- it can be interpreted that we will be using the first 21 out of the 30 overall colors.

**Comment by tzanio** [comment]
Ok, I'll make the change

**Comment by tzanio** [comment]
> Perhaps it makes sense for the discretization option to come after selecting the palette in the F6 menu (otherwise the the denominator in the displayed number of colors won't reflect the new choice).

Done in 17493e1.

Had to split `Select_New_RGB_Palette()` in two for that.

**Comment by tzanio** [comment]
@pazner, did 17493e1 address your concerns?

**Comment by tzanio** [comment]
Merged in `next` for testing...

**Pull request merged**
