### PR TITLE
Adding support for pyramid shaped elements [pyramid-dev]

### PR DESCRIPTION
**Pull request by mlstowell**
Pyramid support is still experimental. Currently, viewing a mesh containing pyramids works and creating a cut plane with 'i' also works.

I still need to revisit ` VisualizationSceneSolution3d::DrawRefinedPyramidLevelSurf` to see if we can/should implement the more elaborate algorithm.

Depends on https://github.com/mfem/mfem/pull/2400

### CODE REVIEW

**Comment by tzanio** [comment]
I merged master in this branch so the server works on a Mac with https://github.com/mfem/mfem/pull/2400/

**Comment by tzanio** [comment]
Now that mfem/mfem#2400 is merged and glvis-4.1 is released, should we consider this PR for merging?

**Comment by tzanio** [comment]
@mlstowell, please indicate when this is ready

**Comment by tzanio** [comment]
ping: @mlstowell

**Comment by tzanio** [comment]
ping: @mlstowell

**Comment by mlstowell** [comment]
Thanks ,@tzanio, it should be ready to go.

**Review by tzanio — APPROVED** [review]
This looks good to me, thanks @mlstowell !

@v-dobrev, @brendankeith or @kanye-quest -- do you want to take a look?

**Comment by brendankeith** [comment]
Looks good to me!

**Review by brendankeith — APPROVED** [review]

**Comment by tzanio** [comment]
thanks @brendankeith !

**Pull request merged**
