### PR TITLE
change test data back to newest version

### PR DESCRIPTION
**Pull request by justinlaughlin**
A recent push inadvertently changed the data to an older version. `test.distanced.saved.png` (test 2) was updated about 5 months ago https://github.com/GLVis/data/commit/81de802ad63ba41cd1fcd3825fbb3d2471538ace. The difference in images is causing test 2 to fail. This just points the submodule to the latest version

### CODE REVIEW

**Comment by justinlaughlin** [comment]
Hopefully this fixes the test 🤞

**Comment by najlkin** [comment]
See #286 , we have fixed that there :wink: .

**Comment by justinlaughlin** [comment]
> See #286 , we have fixed that there 😉 .

Ah nice, I just started looking through your PR and was about to comment 😅. Thanks!

**Comment by tzanio** [comment]
Sorry about this, my fault for missing the submodule dependence

**Pull request closed without merging**
