### PR TITLE
Fixed Shift combinations with different keyboard layouts

### PR DESCRIPTION
**Pull request by najlkin**
This is a possible fix for #308 . Please test it!

### CODE REVIEW

**Comment by justinlaughlin** [comment]
Something funky going on with test 11 `mesh-explorer` on mac 👀 

image

**Comment by najlkin** [comment]
What is that !? 🙃

**Comment by najlkin** [comment]
Can you test it @justinlaughlin ? I do not have a Mac 🍏 ...

**Comment by justinlaughlin** [comment]
> Can you test it @justinlaughlin ? I do not have a Mac 🍏 ...

I don't have one either unfortunately 🏠🐧

**Comment by najlkin** [comment]
Ok, I maybe know what happens, `SdlWindow::signalKeyDown()` generates also these key down events, but does not initialize the scan code, which did not matter before, but matters now 🤔 .

**Comment by najlkin** [comment]
Ok, still some keys are handled in `keyDownEvent()` instead of `textInputEvent()`, but it does not matter, I would say, as the called functions are identified by the key code, which is always correct from `signalKeyDown()`.

**Comment by tzanio** [comment]
I can confirm that the latest commit shows the mesh-explorer test correctly on my mac

**Review by tzanio — APPROVED** [review]
I tested some more, and this appears to work as before with the standard layout on Mac

**Comment by justinlaughlin** [comment]
FWIW, tested `mesh-explorer` on WSL and it seems to be fine.

**Review by justinlaughlin — APPROVED** [review]

**Comment by najlkin** [comment]
@justinlaughlin  Do you have different layouts than the US?

**Comment by justinlaughlin** [comment]
> @justinlaughlin Do you have different layouts than the US?

Just USA 🦅

**Pull request merged**
