### PR TITLE
WebGL 2 support

### PR DESCRIPTION
**Pull request by kanye-quest**
- For Emscripten, probe for WebGL 2 context support (supported on Firefox, Chrome)
- Use sized texture formats required for supporting floating-point textures in WebGL 2
- When available, use framebuffer objects to support antialiasing; available for OpenGL 3+ and WebGL 2

### CODE REVIEW

**Review by tzanio — APPROVED** [review]
I know @tomstitt saw some issues, but this works great for me. Thanks @kanye-quest !

Screen Shot 2020-12-28 at 1 51 17 PM

**Comment by tzanio** [comment]
One todo -- please document in `CHANGELOG`

**Comment by tzanio** [comment]
This continues to work great for me. @tomstitt do you have a way to test the https://github.com/GLVis/glvis/pull/138#issuecomment-751938077 issue without deploying?

**Comment by tomstitt** [comment]
> This continues to work great for me. @tomstitt do you have a way to test the [#138 (comment)](https://github.com/GLVis/glvis/pull/138#issuecomment-751938077) issue without deploying?

I tested locally and it's looking good now. Thanks @kanye-quest !

**Comment by tzanio** [comment]
Any objections to merge #138 here and then merge this in `master`?

**Comment by tomstitt** [comment]
> Any objections to merge #138 here and then merge this in `master`?

The only other thing I'm seeing is a link warning: `warning: metadce: missing declaration for emcc$export$dynCall_vi`.
I tested a function call to a something with what I think the `vi` signature is (`void (*)(int)`) and it worked fine so I'm not sure what's actually missing. @kanye-quest pointed out that a similar issue was fixed in https://github.com/emscripten-core/emscripten/pull/6444.

**Review by tomstitt — APPROVED** [review]

**Comment by tzanio** [comment]
> I tired with -O2 and the warning goes away.

I can confirm this works for me too

**Pull request merged**
