### PR TITLE
move mesh division in 2d to key 'o' for consistency with 3d

### PR DESCRIPTION
**Pull request by rw-anderson**
Changes the interface to be a little more consistent with 2d and 3d for refining elements.  Both now use o/O.

Addresses #99.

### CODE REVIEW

**Comment by tzanio** [comment]
Can you please document in `CHANGELOG`?

**Comment by rw-anderson** [comment]
Sure, shall I just push it to the v4.0-dev branch?

**Comment by tzanio** [comment]
No, lets do it here. I will merge it there.

**Comment by tzanio** [comment]
Should we switch also `w` in 2D to `i`?

**Comment by v-dobrev** [comment]
> Should we switch also `w` in 2D to `i`?

Sounds good to me.

**Review by v-dobrev — APPROVED** [review]

**Comment by tzanio** [comment]
> Should we switch also `w` in 2D to `i`?

Done in https://github.com/GLVis/glvis/pull/126/commits/6bd96363458ab272a91e81613f23ccf49770fabc

**Review by tzanio — APPROVED** [review]
Thanks @rw-anderson !

**Comment by tzanio** [comment]
@kanye-quest are you OK with this PR?

**Review by kanye-quest — APPROVED** [review]
LGTM

**Pull request merged**
