### PR TITLE
Fix parallel visualization of meshes without solution

### PR DESCRIPTION
**Pull request by dalcinl**

### CODE REVIEW

**Comment by tzanio** [comment]
Cool, thanks!

**Comment by dalcinl** [comment]
@tzanio Oh! Sorry! I merged too quickly, I should have waited for the review of @v-dobrev

**Comment by tzanio** [comment]
Yes, no worries :)

**Comment by dalcinl** [comment]
Anyway, my changes did not change the previous behavior in any way (the handling of `mesh` is parallel was broken), so I think there is no pressure to revert this PR.

**Comment by tzanio** [comment]
Don't revert... @v-dobrev do you mind taking a quick look?

**Comment by v-dobrev** [comment]
Looks good to me. I did not actually test it but that's OK.

One more thing, we should try to follow the same merging procedure as in mfem: first merge manually in the `next` branch for testing, and then after about a week, merge in `master`.

**Comment by tzanio** [comment]
@dalcinl: After some discussion we decided to merge an approved PR first into the `next` branch, add the `in-next` label, and then merge into `master`.

For now we will skip the weekly wait between the two merges, as `glvis:next` is not currently tested. This may change in the future...

**Pull request merged**
