### PR TITLE
Final changes for glvis-4.1

### LINKED ISSUE #182: The web version at `glvis.org/live` does not detect hi-DPI display
As a result, fonts are smaller than intended as in the desktop version.

### PR DESCRIPTION
**Pull request by tzanio**
This will be the last PR to be merged before the glvis-4.1 release.

**Release date** 

August 27th (Friday)  ~August 31st, 2021 (Tuesday) or earlier~

**Completed Tasks**

- [x] ~Merge #189~
- [x] ~Merge https://github.com/GLVis/glvis/pull/190~
- [x] ~Propagate `glvis/data` changes in `glvis-js`: https://github.com/GLVis/glvis-js/pull/10~
- [x] ~Propagate `glvis/data` changes in `pyglvis`: https://github.com/GLVis/pyglvis/pull/21~
- [x] ~Remove mentioning of `glvis::out` and `glvis::err` from `CONTRIBUTING.md`~
- [x] ~Merge #192~
- [x] ~Merge #193~
- [x] ~Merge #188~
- [x] ~Resolve https://github.com/GLVis/pyglvis/issues/22~
- [x] ~Mention xeus-glvis in `CHANGELOG`~
- [x] ~Mention new `glvis/data` repo~
- [x] ~Resolve #182 -- see https://github.com/GLVis/glvis/pull/196 and https://github.com/GLVis/glvis-js/pull/12~
- [x] ~Resolve https://github.com/GLVis/pyglvis/issues/5 -- see https://github.com/GLVis/glvis/pull/195, https://github.com/GLVis/glvis-js/pull/11 and https://github.com/GLVis/pyglvis/pull/25~
- [x] ~Merge https://github.com/GLVis/glvis/pull/197~
- [x] ~Merge #191~

### CODE REVIEW

**Comment by tzanio** [comment]
@tomstitt, should we mention https://github.com/GLVis/xeus-glvis in the CHANGELOG?

**Comment by tomstitt** [comment]
> @tomstitt, should we mention https://github.com/GLVis/xeus-glvis in the CHANGELOG?

When do you want to do the release by? I'd like to get a working binder example before we mention it. I'll work on that this week

**Comment by tzanio** [comment]
> When do you want to do the release by? 

The target date for the release is August 31st.

**Review by tomstitt — APPROVED** [review]
🎉

**Review by kanye-quest — APPROVED** [review]

**Pull request merged**
