### PR TITLE
Another fix for MPI+X11 error

### LINKED ISSUE #120: Building issue with MFEM built with MPI support on Linux
This issue with X11 and MPI was reported here: https://github.com/GLVis/glvis/pull/66#issuecomment-738282716 and unfortunately was not fully resolved by 8fe6bdd. We still have `sdl.cpp` includes `threads.hpp` which includes `mfem.hpp` which includes `mpi.h` (when MFEM is built with MPI). On the other hand `sdl.cpp` also includes `sdl_x11.hpp` --> `X11/extensions/XInput2.h` --> `X11/Xlib.h`.

cc: @termi-official, @kanye-quest, @tzanio

### PR DESCRIPTION
**Pull request by kanye-quest**
Closes #120.

### CODE REVIEW

**Review by tzanio — APPROVED** [review]

**Comment by v-dobrev** [comment]
This still does not work.

Somewhat unrelated: I'm also seeing issues with the Intel compiler on Quartz in `glm`.

**Comment by kanye-quest** [comment]
The latest change seems to have fixed the build for me, at least while building with GCC.

**Comment by v-dobrev** [comment]
Un-defining `Status` is actually not necessary now. Should we revert that change?

**Comment by kanye-quest** [comment]
That's fine by me.

**Review by v-dobrev — APPROVED** [review]

**Pull request merged**
