### PR TITLE
Replace deprecated GetOrder with GetElementDegree.

### PR DESCRIPTION
**Pull request by jakubcerveny**
Update use of GetOrder due to `var-order-space-dev`

### CODE REVIEW

**Comment by tzanio** [comment]
Review after https://github.com/mfem/mfem/pull/1817 is merged

**Comment by tzanio** [comment]
Sorry, there are now conflicts in this PR that need to be resolved due to recent restructuring.

cc: @kanye-quest

**Comment by kanye-quest** [comment]
Yeah, `ProjectVectorFEGridFunction` is now in `stream_reader.cpp` instead of `glvis.cpp`, so the change in this PR should be made there.

**Comment by jakubcerveny** [comment]
Invalidated by https://github.com/mfem/mfem/pull/2075

**Comment by jakubcerveny** [comment]
Closing...

**Pull request closed without merging**
