### PR TITLE
Extended copyright to 2022

### PR DESCRIPTION
**Pull request by tzanio**
`Copyright (c) 2010-2021` -> `Copyright (c) 2010-2022`

### CODE REVIEW

**Review by adrienbernede — APPROVED** [review]
Looks good to me, I couldn’t find another 2021 to update.
I guess tests are failing on the branch root too?

**Comment by tzanio** [comment]
Tests seem to be timing out for some reason... @kanye-quest do you have any ideas why?

**Comment by kanye-quest** [comment]
That's really odd - maybe something about the github action VMs changed?

We probably need to see the generated screenshots to debug this. In the builds.yml file:

https://github.com/GLVis/glvis/blob/6e2b9fcd9d47498c2e32592f68e68790461bb5d0/.github/workflows/builds.yml#L228-L229

should be changed to:

```yaml
     - name: upload test screenshots 
       if: always() && matrix.build-system == 'cmake' 
```

That should give us the tarball of the generated screenshots even if the tests fail.

**Comment by tzanio** [comment]
OK, I made the change in [24f2d47](https://github.com/GLVis/glvis/pull/221/commits/24f2d47bdeb4587651f13b0909c582c8089ea7d3)

**Comment by kanye-quest** [comment]
Yeah, after looking at the test log, I'm guessing its the result of an upgraded Mesa version on the Ubuntu VMs.

Version string from the last passing actions run: `Using GL 3.1 Mesa 21.0.3`
And from our current failing runs: `Using GL 3.1 Mesa 21.2.6`

We might just have to generate new baselines - I pushed one more change to the actions file for that.

**Review by camierjs — APPROVED** [review]

**Comment by tzanio** [comment]
I will wait on merging this until we figure out the testing issue

**Pull request merged**
