### PR TITLE
Move OpenGL modernization changes to GLVis

### PR DESCRIPTION
**Pull request by kanye-quest**
This pull request moves work done on #61 to a branch in the main repository.

### CODE REVIEW

**Comment by tzanio** [comment]
Here is an example of @kanye-quest's work based on these changes -- GLVis running in a browser!

libglvis js

**Comment by jakubcerveny** [comment]
This is an impressive body of work, it will take me some time to go over. Also, I still need to wrap my head around the emscripten stuff, I'm still trying to figure out how that works.

**Comment by jakubcerveny** [comment]
@kanye-quest, would you mind adding a description for this PR? What are the main changes? Can this be merged into master while retaining all functionality (i.e., is this "production" code, not experimental)?

**Comment by kanye-quest** [comment]
This PR still needs more work before being merged into master, so I think for now I'll pull the changes into a branch and create a PR from there, so others can work on it as well.

**Pull request closed without merging**
